travis:
  secure:
    BINSTAR_TOKEN: Q8qExLzvW1H2ItPpHna6EGfrhgcmwb4KXZRihA7pPiwca51NqpZMswo5hmrRyLwPIpv5uS8oNDkaxcValRFUwfmVZppPQpsj+V0LyLdxdmoju0ADjdg//ff2489aBXPpDBBZCIwbNAt8d76/BP4DZjzEMcOlVhdK0FVDKm9EP0S++GVjO8reuKF3RkSlFJZbwuk9//9/sOGEVb3gdcQD6EK2PiVZ3cfPdO2/XawWdXuzOou3wGPYuTE8z2NtKA5WZBN+Cjqk/q1d0Sb91qhdnskdva85AiEtZS2+QPiFcs1t/jLo4hvuqYSX+OCXCgEfjc9Qa2lx05dIQoeoTU2holqAa/Cy1reeANyGQUI4GkXYwX+UOiGJKvHDR7G+xvv8kNqGaOOtibDd1gN8BwqwnnjqOS4Z/uYjq5PnIXnwfPPUwcObXxIsqA3Tt+mTL51X/LBqIWRsN9ftmnZ88n7UHcorl7aaGNcBMA0y6SwKc254JYqj91sxGkPKtKabk3sCesz0JRVNgizeGq9Oq4BijvIc641WKttkcfZT/YhvO7kjca1g+afSktjJqdFQQVhz9NyHVD4xexiJl0rc/35pu2KbrKN+LXs8k/rYsnsju+g4reAMayzNHK/0IRUsYX1kjI8C6FEklQQKWTTqKBRUPYUdATqGZyVHZxEqMPmLSTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
